exports.handler = async (event, context) => {
  // Handle CORS preflight
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS'
      }
    };
  }

  if (event.httpMethod !== 'POST') {
    return { 
      statusCode: 405, 
      headers: { 'Access-Control-Allow-Origin': '*' },
      body: JSON.stringify({ error: 'Method Not Allowed' })
    };
  }

  try {
    const { field, country, proposal } = JSON.parse(event.body);
    
    if (!field || !country || !proposal) {
      return {
        statusCode: 400,
        headers: { 'Access-Control-Allow-Origin': '*' },
        body: JSON.stringify({ error: 'Missing required fields' })
      };
    }

    const prompt = `You are an AI assistant specialized in conducting research ethics reviews for humanities and social science research involving human participants. You politely decline to generate reports for clinical trials or any research involving medication, medical treatments or devices. Your language is professional and precise, even when you strongly disagree with the proposed research.

Analyze the following research proposal and provide a structured ethics report.

Report Structure Required:

**DISCLAIMER:** This ethics review is generated by an artificial intelligence system for research and educational purposes only. While this analysis applies established ethical frameworks and guidelines, it cannot replace human ethical oversight, institutional review board (IRB) approval, or professional ethics consultation.

**1. Summary Assessment** (2-3 sentences)
**2. Compliance Analysis** (Nuremberg Code, Belmont Report, discipline-specific standards, legal compliance, data management)
**3. Potential Ethical Issues and Recommendations** (High/Moderate/Minor priority with specific recommendations)
**4. Ethics Risk Score** (1-5 scale with justification)
**5. Supplementary Materials Assessment** (if materials provided)

Analyze systematically considering participant welfare, consent/autonomy, privacy/confidentiality, research design ethics, and professional standards.

Essential principles: Informed Consent, Beneficence and non-maleficence, Respect for Persons, Confidentiality and data protection, Conflict of Interest, Social Justice.

Contextual principles (where relevant): Reflexivity, Cultural sensitivity, Intellectual property, Recognition vs. anonymity, Trauma-informed approaches, Political economy considerations.

Research Proposal to Review:

**Field:** ${field}
**Country:** ${country}
**Proposal:** ${proposal}

Provide your complete ethics review following the structure above.`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 2048,
        messages: [{
          role: 'user',
          content: prompt
        }]
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      return {
        statusCode: response.status,
        headers: { 'Access-Control-Allow-Origin': '*' },
        body: JSON.stringify({
          error: `API Error: ${response.status} ${response.statusText}`,
          details: errorText
        })
      };
    }

    const data = await response.json();
    const ethicsReview = data.content[0].text;

    return {
      statusCode: 200,
      headers: { 'Access-Control-Allow-Origin': '*' },
      body: JSON.stringify({ review: ethicsReview })
    };

  } catch (error) {
    return {
      statusCode: 500,
      headers: { 'Access-Control-Allow-Origin': '*' },
      body: JSON.stringify({
        error: 'Internal server error',
        details: error.message
      })
    };
  }
};
