const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// HARDCODED API KEY - Replace with your actual API key
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
console.log('API Key loaded:', ANTHROPIC_API_KEY ? 'YES' : 'NO');
// Middleware
app.use(cors({
    origin: ['https://radiant-sunshine-56d1ce.netlify.app', 'http://localhost:3000'],
    credentials: true
}));
app.use(express.json());
app.use(express.static('public'));

// Serve the HTML file
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// API endpoint for ethics review
app.post('/api/ethics-review', async (req, res) => {
    try {
        const { field, country, proposal } = req.body;

        if (!field || !country || !proposal) {
            return res.status(400).json({ error: 'Missing required fields' });
        }

        const response = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': ANTHROPIC_API_KEY,
                            },
            body: JSON.stringify({
                model: 'claude-sonnet-4-20250514',
                max_tokens: 2048,
                messages: [{
                    role: 'user',
                    content: `You are an AI assistant specialized in conducting research ethics reviews for humanities and social science research involving human participants. You politely decline to generate reports for clinical trials or any research involving medication, medical treatments or devices. Your language is professional and precise, even when you strongly disagree with the proposed research.

Analyze the following research proposal and provide a structured ethics report.

Report Structure Required:

**DISCLAIMER:** This ethics review is generated by an artificial intelligence system for research and educational purposes only. While this analysis applies established ethical frameworks and guidelines, it cannot replace human ethical oversight, institutional review board (IRB) approval, or professional ethics consultation.

**1. Summary Assessment** (2-3 sentences)
**2. Compliance Analysis** (Nuremberg Code, Belmont Report, discipline-specific standards, legal compliance, data management)
**3. Potential Ethical Issues and Recommendations** (High/Moderate/Minor priority with specific recommendations)
**4. Ethics Risk Score** (1-5 scale with justification)
**5. Supplementary Materials Assessment** (if materials provided)

Analyze systematically considering participant welfare, consent/autonomy, privacy/confidentiality, research design ethics, and professional standards.

Essential principles: Informed Consent, Beneficence and non-maleficence, Respect for Persons, Confidentiality and data protection, Conflict of Interest, Social Justice.

Contextual principles (where relevant): Reflexivity, Cultural sensitivity, Intellectual property, Recognition vs. anonymity, Trauma-informed approaches, Political economy considerations.

Research Proposal to Review:

**Field:** ${field}
**Country:** ${country}
**Proposal:** ${proposal}

Provide your complete ethics review following the structure above.`
                }]
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            return res.status(response.status).json({
                error: `API Error: ${response.status} ${response.statusText}`,
                details: errorText
            });
        }

        const data = await response.json();
        const ethicsReview = data.content[0].text;

        res.json({ review: ethicsReview });

    } catch (error) {
        console.error('Error:', error);
        res.status(500).json({
            error: 'Internal server error',
            details: error.message
        });
    }
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
